name: flowter_example
description: "Empty example project demonstrating basic Flowter usage"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Flowter core package
  flowter_core:
    path: ../flowter_core

  # flowter_python:
  #   path: ../io/flowter_python

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
